# The key is the exact name of the label you want to apply
# The value is the regex pattern to match against the title and body

urgent:
  - '(urgent|critical|asap|blocker)'

bug:
  - '(bug|broken|error|crash|failing|fix|issue)'

documentation:
  - '(docs|documentation|readme|typo)'

enhancement:
  - '(enhancement|feature|feat|improvement|suggestion)'

test:action:
  - '/.*/'